### ISSUE TITLE
Add ability to choose linters to run

### ISSUE THREAD

**Issue by steelbrain** [joefitzgerald/gometalinter-linter#4] opened 2016-01-17 16:39 UTC
Currently it executes all of available linters, which results in duplicate messages. It would be nice to be able to choose the linters to be executed.

**Comment by joefitzgerald** [comment] 2016-01-17 17:08
Duplicate of #3.

**Comment by steelbrain** [comment] 2016-01-17 17:08
Oops, I thought it was about something else

**Closed as completed by joefitzgerald** 2016-01-17 17:08 UTC
